[build]
publish = "my-site/public" # Ensure this matches your Hugo output directory
command = "cd my-site && hugo --gc --minify --enableGitInfo --themesDir themes"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
[context.production.environment]
HUGO_VERSION = "0.143.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_THEME = "hugo-profile"

[context.split1]
command = "cd my-site && hugo --gc --minify --enableGitInfo --themesDir ../.."

[context.split1.environment]
HUGO_VERSION = "0.143.0"
HUGO_ENV = "production"
HUGO_THEME = "hugo-profile"

[context.deploy-preview]
command = "cd my-site && hugo --gc --minify --buildFuture --themesDir themes -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.143.0"
HUGO_THEME = "hugo-profile"

[context.branch-deploy]
command = "cd my-site && hugo --gc --minify --themesDir themes -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.143.0"

